### ISSUE TITLE
Menu overlapping

### ISSUE THREAD

**Issue by Guillaume99** [juliushaertl/direct_menu#32]
When resizing the browser window, the menu is ovelapping with the search icone before being removed. See attached picture (Firefox 48, Nextcloud 9.0.53, Direct Menu 0.9)...

![menu ok](https://cloud.githubusercontent.com/assets/20171421/17832057/aa61cee0-66fa-11e6-87c7-e1f1ffd2cc78.png)
![menu overlap](https://cloud.githubusercontent.com/assets/20171421/17832056/aa5d8e34-66fa-11e6-94c8-76a30f9e538a.png)
![menu removed](https://cloud.githubusercontent.com/assets/20171421/17832058/aa628d3a-66fa-11e6-8fc5-ebcf596a3580.png)

**Comment by juliusknorr** [comment]
This is something we can't fix that easy, as the width of the menu depends on the number of apps you have installed. But yes, this is something that sould be fixed.

**Comment by juliusknorr** [comment]
@Guillaume99 This should be fixed now on master. Would be great if you could do some testing.

**Comment by Guillaume99** [comment]
hello Julius,

I did some testing with NC10 and the master branch, but it is still overlapping … :-(

**Comment by juliusknorr** [comment]
Have you installed the master release by downloading a zip from Github?
Can you make sure that there are only the files present that are now on
the current master?

The best would be to remove the entire direct_menu folder before
extracting the "master"-zip. Otherwise there are a couple of files from
the old version, that don't get removed.

If it still doesn't work with a clean direct_menu folder, could you
check if https://yourclouddomain.com/index.php/apps/direct_menu/styles
is loaded (use your browser debugging tools by hitting F12)

**Comment by Guillaume99** [comment]
hello Julius,

yes, that exactly how I installed your app… but I stil have the problem, so I did a little investigation and found where it came from.

For any reason, the « Tasks » app is not counted, you can add or remove it, the min-width value will not change ! 

This is probably not related to your code, and your application is quite good now !

Guillaume

update : the ownNote is doing the same...

**Comment by juliusknorr** [comment]
Ah, ok i'll have a look what might go wrong therr.

**Comment by powerpaul17** [comment]
I just noticed that if I use the search icon in an app which supports it, the opening input field still overlaps the menu icons.

**Comment by juliusknorr** [comment]
@powerpaul17The overlapping search box has been fixed now in #58.Thanks for the hint.

**Comment by powerpaul17** [comment]
Thank you, you're welcome.
