### ISSUE TITLE
Owncloud 10 update

### ISSUE THREAD

**Issue by MoBOatGVA** [juliushaertl/direct_menu#61]
Hello,

pretty sure the answer will be "Yes" but I do prefer to ask : did you planned a compatible version for owncloud 10 ?

Thanks for the work already done.

Regards,

Mo

**Comment by juliusknorr** [comment]
I don't have any OwnCloud instance for testing any more but if they did not change to much it should still work by changing the max-version in appinfo/info.xml. Pull requests are welcome, but I will not put further effort into the development of this app, since Nextcloud 12 comes with a new menu on top.

**Comment by ravermeister** [comment]
so does that mean I should remove this App before Upgrading to Nextcloud 12?

**Comment by juliusknorr** [comment]
@ravermeister No, it will just be disabled when you upgrade to Nextcloud 12.

**Comment by blackcrack** [comment]
by the way, i have see many numbers without indicated by type like blabla:0; 
right it is blabla:0px; this it is then more correct, because many browsers 
do not use this automatic as pixel this is it why you are should ever set the type of the number. 
and you want see, many works suddenly what have not works before ;)

and julius, can you maybe speak with the master of designer (\*bg\*)
to he set the design of menu the used style id=menusmall and id=menudirect
or maybe id=customenubig id=customenusmall id=menuandroid 
by resolution of the Monitor and adjustable in the Adminaccount
by activate plugins (the menu as plugin) and the id controlled by java or so to be able
to able customation the menu fully as css theme... (with this can you spare the phpthemplate
and can make as fully css-compatieble menu by #direct-menu-navigation and something)
directly in the nextcloud to be it possible for set up per css the directmenu and add it 
size,space and so on (right space on top) for be able to make better css designs
and better to adjust :)

best regards
blacky

**Comment by juliusknorr** [comment]
@blackcrack According to the CSS standard units are optional when the value is zero. 

https://www.w3.org/TR/CSS2/syndata.html#length-units

>  After a zero length, the unit identifier is optional.

**Comment by blackcrack** [comment]
👍
